# Generated by Django 3.1.7 on 2021-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20210315_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mood',
            field=models.CharField(choices=[('TURNUP', 'Turn Up'), ('CHILL', 'Chill'), ('STUDY', 'Study')], default='Chill', max_length=1000),
        ),
    ]
