# Generated by Django 3.1.7 on 2021-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_auto_20210320_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mood',
            field=models.FloatField(choices=[(0.8, 'Turn Up'), (0.5, 'Chill'), (0.3, 'Study')], default=(0.8, 'Turn Up'), max_length=1000),
        ),
    ]
