# Generated by Django 3.1.7 on 2021-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_auto_20210323_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_track',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
