# Generated by Django 3.1.7 on 2021-03-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('RAP', 'Rap'), ('LOFI', 'Lofi'), ('POP', 'Pop'), ('ELECTRO', 'Electro'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz')], max_length=100)),
                ('mood', models.CharField(choices=[('TURNUP', 'Turn Up'), ('CHILL', 'Chill'), ('STUDY', 'Study')], max_length=1000)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.artist')),
            ],
        ),
    ]
