# Generated by Django 3.1.7 on 2021-03-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_auto_20210319_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
